index/index/urls.py
from django.conf.urls import patterns, include, url
from cite.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'index.views.home', name='home'),
    # url(r'^index/', include('index.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    ('^$', hello),
    ('^author$', author_list),
    ('^author/(?P<author_id>\d*)$', author_detail),
    ('^author/json/(?P<author_id>\d*)$', author_json),
    ('^paper$', paper_list, None),
    ('^paper/(?P<paper_id>\d*)$', paper_detail),
    ('^paper/json/(?P<paper_id>\d*)$', paper_json),
    ('^token/(?P<token_id>\d*)$', token_lookup),
    ('^search$', topic_search),

)

index/cite/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=80, unique=True)
    def __unicode__(self):
        return self.name

class Paper(models.Model):
    title = models.CharField(max_length=255, unique=True)
    filename = models.CharField(max_length=255, unique=True, blank=True, null=True, default=None)
    authors = models.ManyToManyField(Author)
    citations = models.ManyToManyField('self', symmetrical=False)
    length = models.IntegerField()
    #if we want to put the abstract in the DB, add it here...
    def __unicode__(self):
        return self.title

class Token(models.Model):
    stem = models.CharField(max_length=40, unique=True)
    #not sure if we need this field, though it might be useful
    total = models.IntegerField()
    df = models.IntegerField(default=0)
    def __unicode__(self):
        return self.stem

class PaperToken(models.Model):
    """many-many relationship of paper<->token with a count"""
    num = models.IntegerField()
    paper = models.ForeignKey(Paper)
    token = models.ForeignKey(Token)
    def __unicode__(self):
        return "%s %s %d" % (unicode(self.token), unicode(self.paper), self.num)

index/cite/forms.py
from django import forms

class TopicSearchForm(forms.Form):
    block = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        """sets the class to 'span12' so it matches the rest of the page to begin with"""
        super(TopicSearchForm, self).__init__(*args, **kwargs)
        self.fields['block'].widget.attrs['class'] = 'span12'
    
    def clean_block(self):
        txt = self.cleaned_data['block']
        topics = 0
        for line in self.cleaned_data['block'].splitlines():
            line=line.strip()
            if len(line) == 0:
                continue
            topics += 1
        if topics < 3:
            raise forms.ValidationError("Probably a good idea to have at least three topics...")
        return txt

index/index/templates/author_detail.html
{% extends "base.html" %}

{% block title %}Author Details{% endblock %}
{% block subtitle %} {{ author }} {% endblock %}

{% block content %}

{% include "author_detail_graph.html" with id=author.id %}

  <h2>Papers</h2>


  <div class="accordion" id="paperaccordion">
  {% for paper in author.paper_set.all %}

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#paperaccordion" href="#collapse{{paper.id}}">{{paper|truncatechars:80}}</a>
    </div>
    <div id="collapse{{paper.id}}" class="accordion-body collapse">
      <div class="accordion-inner">
        {{paper}}
        <ul class="nav nav-list">
          <li><a href="/paper/{{paper.id}}">Paper Details</a></li>
          <br />Other Authors: 
          {% for pauthor in paper.authors.all %}
          <li><a href="/author/{{pauthor.id}}">{{ pauthor }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

  {% endfor %}
  </div> <!-- accordion -->

{% endblock %}

index/index/templates/author_detail_graph.html
    <div class = "well well-small">
      <div class = "graph">
<!--
The basic gist of this template came from http://graus.nu/d3/
-->
      <script type="text/javascript" src="/static/d3.v3.min.js"></script>

      <style type="text/css">
          node { 
              stroke-width: 1.5px;
              }
          .graph {
              margin:0 auto;
              width:900px;
              color:#FFF;
              border: 1px dashed #333;
              }
          line {
              stroke: #666;
              }
      </style>
      </div>
    </div>
    
    <script type="text/javascript">

var w = 900, h = 700, r = 10;

var win = d3.select(".graph")
    .append("svg:svg")
    .attr("width", w)
    .attr("height", h)
    .attr("pointer-events", "all")
var vis = win
    .append('svg:g')
    .call(d3.behavior.zoom().on("zoom", redraw))
    .append('svg:g');

vis.append('svg:rect')
    .attr('width', w)
    .attr('height', h)
    .attr('fill', 'rgba(1,1,1,0)')

var infofield = win.append('svg:g')
    .attr('class', 'info')
    .append('svg:text')
    .attr('x', 5)
    .attr('y', h-5 )
    .text("")

function redraw() {
    console.log("here", d3.event.translate, d3.event.scale);
    vis.attr("transform","translate(" + d3.event.translate + ")" + " scale(" + d3.event.scale + ")"); }
    
    var force = d3.layout.force()
        .gravity(.05)
        .charge(function(d){
            if(d.size > 10) {
                return -2000;}
            else {return -200;};
        })
        .linkDistance(function(d){
            return 30;
        })
        .size([w, h]);
    
    var svg = d3.select(".text").append("svg")
        .attr("width", w)
        .attr("height", h);
        
d3.json("/author/json/{{id}}", function(json) {
        var link = vis.selectAll("line")
            .data(json.links)
            .enter().append("line")
            .attr("stroke-opacity", function(d) { if(d.label == 'is a') { return '0.8';} else{ return '0.2'; }; })
            .attr("stroke-width","6")
            .style("stroke", function(d) { if(d.color !== null) { return d.color;}; })
            .on("mouseover", function(){d3.select(this).style("stroke", "#999999").attr("stroke-opacity", "1.0");})
            .on("mouseout", function(){d3.select(this).style("stroke", function(d) { if(d.color !== null) { return d.color;}; }).attr("stroke-opacity", function(d) { if(d.label == 'is a') { return '0.8';} else { return '0.2'; };}) });

        var node = vis.selectAll("g.node")
            .data(json.nodes)
            .enter().append("svg:g")
            .attr("class","node")
            .on("mouseover", onMouseOver)
            .on("mouseout", onMouseOut)
            .call(force.drag);

            node.append("svg:circle")
                .attr("r", function(d){
                    if (d.size < 10) { d.size = 10 } 
                    return d.size;})
                .style("fill", "#888")
                
            node.append("svg:text")
                .attr("text-anchor", "middle") 
                .style("pointer-events", "none")
                .attr("font-size", function(d) { if (d.color == '#b94431') { return 10+(d.size*2) + 'px'; } else { return "9px"; } } )
                .attr("font-weight", function(d) { if (d.color == '#b94431') { return "bold"; } else { return "100"; } } )
                .text( function(d) { if (d.color == '#b94431') { return d.id + ' (' + d.size + ')';} else { return d.id;} } ) ;
                
            node.append("title")
                .text(function(d) { return d.URI } );

        force
            .nodes(json.nodes)
            .links(json.links)
            .on("tick", tick)
            .start();

    function onMouseOver(d) {
        //bring the node to the front...
        d3.select("g.info").select("text").text(d.title);
        vis.selectAll("g.node").sort(function(a,b) {
            if(a.id == d.id ) {return 1;}
            return -1;});
        d.hovered = true;
        d3.select(this).select("circle")
            .attr("r", function(d){return d.size*2;})
            .style("fill", "#BBB");
        d3.select(this).select("text")
            .style("pointer-events", "all")
            .style("cursor", "pointer")
            .on("click", function(){window.location = "/author/" + d.id});
    }
    function onMouseOut(d) {
        d3.select("g.info").select("text").text("");
        d.hovered = false;
        d3.select(this).select("circle")
            .attr("r", function(d){return d.size;})
            .style("fill", "#888");
        d3.select(this).select("text")
            .attr("xlink:href", null)
            .style("pointer-events", "none")
            .style("cursor", "default")
            .on("click", null);
    }

            
  function tick() {
    node.attr("cx", function(d) { return d.x; })
        .attr("cy", function(d) { return d.y; })
        .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")";});

    link.attr("x1", function(d) { return d.source.x; })
        .attr("y1", function(d) { return d.source.y; })
        .attr("x2", function(d) { return d.target.x; })
        .attr("y2", function(d) { return d.target.y; });
  }
});

    </script>

index/index/templates/author_list.html
{% extends "base.html" %}

{% block title %}Authors{% endblock %}
{% block subtitle %}Authors{% endblock %}

{% block content %}

  <ul>
{% for author in author_list %}
    <li><a href="/author/{{author.id}}">{{ author }}</a></li>
{% endfor %}
  </ul>


{% endblock %}

index/index/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <script src="/static/jquery-1.9.1.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.css">
</head>

<body>
  <div class = "container">
  <div class = "row">
  <div class = "span12">

  {% block header %}
  <h1>
      {% block subtitle %}{% endblock %}
  </h1>
  {% endblock %}

  {% block content %}{% endblock %}

  {% block footer %}{% endblock %}

  </div>
  </div>
  </div>

</body>
</html>

index/index/templates/frontpage.html
{% extends "base.html" %}

{% block title %}ACL Citation Analysis{% endblock %}
{% block subtitle %}ACL Citation Analysis{% endblock %}

{% block content %}
  Serving {{len1}} Papers by {{len2}} Authors with {{len3}} Tokens<br/>
  <ul>
    <li><a href="/search">Search by topic/keyword</a></li>
    <li><a href="/author">Author List</a></li>
    <li><a href="/paper">Paper List</a></li>
  </ul>

  <strong>Top ten papers by number of papers citing:</strong>
  <div class='well well-small'>
  <table class='table'>
    <tr>
      <th>Paper</th>
      <th>Citing</th>
    </tr>
    {% for paper,num in rcite_list %}
    <tr>
      <td><a href="/paper/{{paper.id}}">{{paper.title}}</a></td>
      <td>{{num}}</td>
    </tr>
    {% endfor %}
  </table></div>

  <strong>Top ten papers by number of citations:</strong>
  <div class='well well-small'>
  <table class='table'>
    <tr>
      <th>Paper</th>
      <th>Citations</th>
    </tr>
    {% for paper,num in cite_list %}
    <tr>
      <td><a href="/paper/{{paper.id}}">{{paper.title}}</a></td>
      <td>{{num}}</td>
    </tr>
    {% endfor %}
  </table></div>


{% endblock %}

index/index/templates/paper_detail.html
{% extends "base.html" %}

{% block title %}Paper Details{% endblock %}
{% block subtitle %} {{ paper }} {% endblock %}

{% block content %}

  Filename: {{paper.filename}} <br/>
  Length: {{paper.length}} <br/>

{% include "paper_detail_graph.html" with id=paper.id %}

  <h2>Authors</h2>
  <div class='well well-small'>
  <ul>
  {% for pauthor in paper.authors.all %}
    <li><a href="/author/{{pauthor.id}}">{{ pauthor }}</a></li>
  {% endfor %}
  </ul>
  </div>

  <h2>Citations</h2>
  <div class='well well-small'>
  <ul>
  {% for cite in paper.citations.all %}
    <li><a href="/paper/{{cite.id}}">{{ cite }}</a></li>
  {% endfor %}
  </ul>
  </div>

  <h2>Papers that cite this one</h2>
  <div class='well well-small'>
  <ul>
  {% for cite in rcitations %}
    <li><a href="/paper/{{cite.id}}">{{ cite }}</a></li>
  {% endfor %}
  </ul>
  </div>

  <h2>Common Tokens</h2>
  <div class='well well-small'>
  <table class='table'>
    <tr><th>Token</th><th>Occurences</th></tr>
    {% for token in common_tokens %}
    <tr>
      <td><a href="/token/{{token.token.id}}">{{token.token}}</a></td>
      <td>{{token.num}}</td>
    </tr>
    {% endfor %}
  </table>
  </div>

  <h2>Uncommon Tokens</h2>
  <div class='well well-small'>
  <table class='table'>
    <tr><th>Token</th><th>Occurences</th></tr>
    {% for token in uncommon_tokens %}
    <tr>
      <td><a href="/token/{{token.token.id}}">{{token.token}}</a></td>
      <td>{{token.num}}</td>
    </tr>
    {% endfor %}
  </table>
  </div>


{% endblock %}

index/index/templates/paper_detail_graph.html
    <div class = "well well-small">
      <div class = "graph">

<!--
The basic gist of this template came from http://graus.nu/d3/
-->
      <script type="text/javascript" src="/static/d3.v3.min.js"></script>

      <style type="text/css">
          node { 
              stroke-width: 1.5px;
              }
          .graph {
              margin:0 auto;
              width:900px;
              color:#FFF;
              border: 1px dashed #333;
              }
          line {
              stroke: #666;
              }
      </style>
      </div>
    </div>
    
    <script type="text/javascript">

var graph = 'graph.json'

var w = 900, h = 700, r = 10;

var win = d3.select(".graph")
    .append("svg:svg")
    .attr("width", w)
    .attr("height", h)
    .attr("pointer-events", "all")
var vis = win
    .append('svg:g')
    .call(d3.behavior.zoom().on("zoom", redraw))
    .append('svg:g');

vis.append('svg:rect')
    .attr('width', w)
    .attr('height', h)
    .attr('fill', 'rgba(1,1,1,0)')

var infofield = win.append('svg:g')
    .attr('class', 'info')
    .append('svg:text')
    .attr('x', 5)
    .attr('y', h-5 )
    .text("")

function redraw() {
    console.log("here", d3.event.translate, d3.event.scale);
    vis.attr("transform","translate(" + d3.event.translate + ")" + " scale(" + d3.event.scale + ")"); }
    
    var force = d3.layout.force()
        .gravity(.05)
        .charge(function(d){
            if(d.size > 10) {
                return -2000;}
            else {return -200;};
        })
        .linkDistance(function(d){
            return 30;
        })
        .size([w, h]);
    
    var svg = d3.select(".text").append("svg")
        .attr("width", w)
        .attr("height", h);
        
d3.json("/paper/json/{{id}}", function(json) {
        var link = vis.selectAll("line")
            .data(json.links)
            .enter().append("line")
            .attr("stroke-opacity", function(d) { if(d.label == 'is a') { return '0.8';} else{ return '0.2'; }; })
            .attr("stroke-width","6")
            .style("stroke", function(d) { if(d.color !== null) { return d.color;}; })
            .on("mouseover", function(){d3.select(this).style("stroke", "#999999").attr("stroke-opacity", "1.0");})
            .on("mouseout", function(){d3.select(this).style("stroke", function(d) { if(d.color !== null) { return d.color;}; }).attr("stroke-opacity", function(d) { if(d.label == 'is a') { return '0.8';} else { return '0.2'; };}) });

            link.append("title")
                .text(function(d) { return d.label } );

        var node = vis.selectAll("g.node")
            .data(json.nodes)
            .enter().append("svg:g")
            .attr("class","node")
            .on("mouseover", onMouseOver)
            .on("mouseout", onMouseOut)
            .call(force.drag);

            node.append("svg:circle")
                .attr("r", function(d){
                    if (d.size < 10) { d.size = 10 } 
                    return d.size;})
                .style("fill", "#888")
                
            node.append("svg:text")
                .attr("text-anchor", "middle") 
                .style("pointer-events", "none")
                .attr("font-size", function(d) { if (d.color == '#b94431') { return 10+(d.size*2) + 'px'; } else { return "9px"; } } )
                .attr("font-weight", function(d) { if (d.color == '#b94431') { return "bold"; } else { return "100"; } } )
                .text( function(d) { if (d.color == '#b94431') { return d.id + ' (' + d.size + ')';} else { return d.id;} } ) ;
                
            node.append("title")
                .text(function(d) { return d.URI } );

        force
            .nodes(json.nodes)
            .links(json.links)
            .on("tick", tick)
            .start();

    function onMouseOver(d) {
        //bring the node to the front...
        d3.select("g.info").select("text").text(d.title);
        vis.selectAll("g.node").sort(function(a,b) {
            if(a.id == d.id ) {return 1;}
            return -1;});
        d.hovered = true;
        d3.select(this).select("circle")
            .attr("r", function(d){return d.size*2;})
            .style("fill", "#BBB");
        d3.select(this).select("text")
            .style("pointer-events", "all")
            .on("click", function(){window.location = "/paper/" + d.id});
    }
    function onMouseOut(d) {
        d3.select("g.info").select("text").text("");
        d.hovered = false;
        d3.select(this).select("circle")
            .attr("r", function(d){return d.size;})
            .style("fill", "#888");
        d3.select(this).select("text")
            .attr("xlink:href", null)
            .style("pointer-events", "none")
            .on("click", null);
    }

            
  function tick() {
    node.attr("cx", function(d) { return d.x; })
        .attr("cy", function(d) { return d.y; })
        .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")";});

    link.attr("x1", function(d) { return d.source.x; })
        .attr("y1", function(d) { return d.source.y; })
        .attr("x2", function(d) { return d.target.x; })
        .attr("y2", function(d) { return d.target.y; });
  }
});

    </script>

index/index/templates/paper_list.html
{% extends "base.html" %}

{% block title %}Papers{% endblock %}
{% block subtitle %}Papers{% endblock %}

{% block content %}

  <ul>
{% for paper in paper_list %}
    <li><a href="/paper/{{paper.id}}">{{ paper }}</a></li>
{% endfor %}
  </ul>


{% endblock %}

index/index/templates/token_lookup.html
{% extends "base.html" %}

{% block title %}Token Lookup{% endblock %}
{% block subtitle %}{{token}}{% endblock %}

{% block content %}

  <ul>
{% for paper in papers %}
    <li><a href="/paper/{{paper.id}}">{{ paper }}</a></li>
{% endfor %}
  </ul>


{% endblock %}

index/index/templates/topic_search_form.html
{% extends "base.html" %}

{% block title %}Token Search{% endblock %}
{% block subtitle %}Token Search{% endblock %}

{% block content %}
    <p>Enter topic search...  The first word of each line is the topic (and
    label for the graph); this word and every other word on the line is used to
    search for documents (using boolean OR) to add to the graph.</p>

    <form action="" method="post">
      <div class="field">
        {% if form.block.errors %}
        <div class="alert alert-error">
          {% for error in form.block.errors %}
          <strong>WARNING:</strong> {{ error }}
          {% endfor %}
        </div>
        {% endif %}
        <label for="id_block">Enter Search:</label>
        {{ form.block }}
      </div>
      <input type="submit" value="Submit" class="btn btn-primary">
    </form>

{% endblock %}

index/index/templates/topic_search_results.html
{% extends "base.html" %}

{% block title %}Token Search Results{% endblock %}
{% block subtitle %}Token Search Results{% endblock %}

{% block content %}

    <h3>Result Graph</h3>
    <div class = "well well-small">
      <div class = "graph">
      <!-- very similar to paper_detail_graph except the results are in the page... -->
      <script type="text/javascript" src="/static/d3.v3.min.js"></script>

      <style type="text/css">
          node { 
              stroke-width: 1.5px;
              }
          .graph {
              margin:0 auto;
              width:900px;
              color:#FFF;
              border: 1px dashed #333;
              }
          line {
              stroke: #666;
              }
      </style>
      </div>
    </div>
    <h3>Result Details</h3>

    <div class="accordion" id="topoicaccordion">
      {% for topic,data in topics.items %}
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#paperaccordion" href="#collapse{{topic}}">{{topic}}</a>
        </div>
        <div id="collapse{{topic}}" class="accordion-body collapse">
          <div class="accordion-inner">
            <strong>Original Query</strong>
            <p>{% for word in data.orig %}{{word}} {% endfor %}</p>
            <strong>Tokens</strong>
            <ul>
              {% for token in data.Tokens %}
              <li><a href="/token/{{token.id}}">{{token.stem}}</a></li>{% endfor %}
            </ul>
            <strong>Number of Papers:</strong> {{data.papers | length}}
          </div>
        </div>
      </div>
    {% endfor %}
    </div> <!-- accordion -->

    
    <script type="text/javascript">

var w = 900, h = 700, r = 10;

var win = d3.select(".graph")
    .append("svg:svg")
    .attr("width", w)
    .attr("height", h)
    .attr("pointer-events", "all")
var vis = win
    .append('svg:g')
    .call(d3.behavior.zoom().on("zoom", redraw))
    .append('svg:g');

vis.append('svg:rect')
    .attr('width', w)
    .attr('height', h)
    .attr('fill', 'rgba(1,1,1,0)')

var json_data = jQuery.parseJSON('{{ json_data|safe }}');

function redraw() {
    console.log("here", d3.event.translate, d3.event.scale);
    vis.attr("transform","translate(" + d3.event.translate + ")" + " scale(" + d3.event.scale + ")"); }
    
    var force = d3.layout.force()
        .gravity(.05)
        .charge(function(d){
            if(d.size > 10) {
                return -2000;}
            else {return -200;};
        })
        .linkDistance(function(d){
            return 100;
        })
        .size([w, h]);
    
    var svg = d3.select(".text").append("svg")
        .attr("width", w)
        .attr("height", h);
        
        var link = vis.selectAll("line")
            .data(json_data.links)
            .enter().append("line")
            .attr("stroke-opacity", '0.2')
            .attr("stroke-width", function(d){return d.width;})
            .style("stroke", function(d) { if(d.color !== null) { return d.color;}; })
            .on("mouseover", function(){d3.select(this).style("stroke", "#999999").attr("stroke-opacity", "1.0");})
            .on("mouseout", function(){d3.select(this).style("stroke", function(d) { if(d.color !== null) { return d.color;}; }).attr("stroke-opacity", function(d) { if(d.label == 'is a') { return '0.8';} else { return '0.2'; };}) });

        var node = vis.selectAll("g.node")
            .data(json_data.nodes)
            .enter().append("svg:g")
            .attr("class","node")
            .on("mouseover", onMouseOver)
            .on("mouseout", onMouseOut)
            .call(force.drag);

            node.append("svg:circle")
                .attr("r", function(d){
                    if (d.size < 10) { d.size = 10 } 
                    return d.size;})
                .style("fill", "#888")
                
            node.append("svg:text")
                .attr("text-anchor", "middle") 
                .style("pointer-events", "none")
                .attr("font-size", function(d) { if (d.color == '#b94431') { return 10+(d.size*2) + 'px'; } else { return "9px"; } } )
                .attr("font-weight", function(d) { if (d.color == '#b94431') { return "bold"; } else { return "100"; } } )
                .text( function(d) { if (d.color == '#b94431') { return d.id + ' (' + d.size + ')';} else { return d.id;} } ) ;
                
            node.append("title")
                .text(function(d) { return d.URI } );

        force
            .nodes(json_data.nodes)
            .links(json_data.links)
            .on("tick", tick)
            .start();

    function onMouseOver(d) {
        //bring the node to the front...
        vis.selectAll("g.node").sort(function(a,b) {
            if(a.id == d.id ) {return 1;}
            return -1;});
        d3.select(this).select("circle")
            .attr("r", function(d){return d.size*2;})
            .style("fill", "#BBB");
        d3.select(this).select("text")
            .style("pointer-events", "all")
            .on("click", function(){window.location = "/paper/" + d.id});
    }
    function onMouseOut(d) {
        d3.select(this).select("circle")
            .attr("r", function(d){return d.size;})
            .style("fill", "#888");
        d3.select(this).select("text")
            .attr("xlink:href", null)
            .style("pointer-events", "none")
            .on("click", null);
    }

            
  function tick() {
    node.attr("cx", function(d) { return d.x; })
        .attr("cy", function(d) { return d.y; })
        .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")";});

    link.attr("x1", function(d) { return d.source.x; })
        .attr("y1", function(d) { return d.source.y; })
        .attr("x2", function(d) { return d.target.x; })
        .attr("y2", function(d) { return d.target.y; });
  }

    </script>

{% endblock %}